# -*- coding: utf-8 -*-
"""0.1-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rayerPGak04_EUjKgr5j0QAGh5UF9nLO
    

# DATA TYPES AND SLICING

###1. **Numeric Data Types**
* integer (int) represents whole number
* floating point type (float) represents decimal numbers
"""

age = 23  #int
pi = 3.14 #float
temperature = -5.5 #float

print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

"""*Slicing into integers and floats*
* TypeErrors will arise from slicing into ints and floats

"""

print(age[0])

print(pi[0])
